=== IUBLibTech/photocat2/photocat-api/src/main/resources/field-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:c="info:photocat/configuration" xmlns:m="info:photocat/metadata"
    targetNamespace="info:photocat/configuration" xmlns="info:photocat/configuration">
    
    <xs:import namespace="info:photocat/metadata" schemaLocation="field-metadata.xsd"/>
    
    <xs:element name="configuration" type="configurationType" />
    
    <xs:complexType name="configurationType">
        <xs:sequence>
            <xs:element ref="collection" />
            <xs:element ref="item" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="collection" type="collectionType" />
    
    <xs:complexType name="collectionType">
        <xs:sequence>
            <xs:element ref="name" />
            <xs:element ref="id" />
            <xs:element ref="description" />
            <xs:element ref="iconURL" />
            <xs:element ref="bannerURL" minOccurs="0" />
            <xs:element ref="allowRecordCreation" />
            <xs:element ref="allowRecordDeletion" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="name" type="xs:string" />
    <xs:element name="id" type="xs:string" />
    <xs:element name="description" type="xs:string" />
    <xs:element name="iconURL" type="xs:string" />
    <xs:element name="bannerURL" type="xs:string" />
    <xs:element name="allowRecordCreation" type="xs:boolean" />
    <xs:element name="allowRecordDeletion" type="xs:boolean" />
    <xs:element name="item" type="itemType" />
    
    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element ref="fields" maxOccurs="unbounded"/>
            <xs:element ref="transformation" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="transformation" type="transformationType" />
    
    <xs:complexType name="transformationType">
        <xs:sequence>
            <xs:element ref="formatName" />
            <xs:element ref="xsltUrl" />
        </xs:sequence>
        <xs:attribute name="id" use="required" type="xs:string" />
        <xs:attribute name="fidelity" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="lossless" />
                    <xs:enumeration value="lossy" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:element name="formatName" type="xs:string" />
    <xs:element name="xsltUrl" type="xs:string" />
    
    <xs:element name="fields" type="fieldsType">
        <xs:unique name="field-type">
            <xs:selector xpath="c:field" />
            <xs:field xpath="@type" />
        </xs:unique>
    </xs:element>
    
    <xs:complexType name="fieldsType">
        <xs:sequence>
            <xs:element ref="field" maxOccurs="unbounded" />
            <xs:element ref="defaultValues" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="definitionId" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="field" type="fieldType" />
    
    <xs:complexType name="fieldType">
        <xs:sequence>
            <xs:element ref="displayLabel" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="attributeDisplayLabel" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="partDisplayLabel" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="usageNotes" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="readOnly" minOccurs="0" />
            <xs:element ref="repeatable" minOccurs="0" />
            <xs:element ref="displayedInCatalogingBriefView" minOccurs="0" />
            <xs:element ref="exposedInCatalogingFullView" minOccurs="0" />
            <xs:element ref="displayedInDiscoveryBriefView" minOccurs="0" />
            <xs:element ref="displayedInDiscoveryFullView" minOccurs="0" />
            <xs:element ref="private" minOccurs="0" />
            <xs:element ref="disable" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="vocabularySource" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:element name="disable">
        <xs:complexType>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="attribute" />
                        <xs:enumeration value="part" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="name" use="required" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="vocabularySource">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="authorityBinding" minOccurs="0" />
                <xs:element ref="valueBinding" />
                <xs:element ref="sourceConfig" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="type" use="required" />
            <xs:attribute name="id" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="valueBinding" type="xs:string" />
    
    <xs:element name="authorityBinding" type="xs:string" />
    
    <xs:element name="sourceConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="property" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="property" type="propertyType" />
    
    <xs:complexType name="propertyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" use="required" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:element name="displayLabel" type="xs:string" />
    <xs:element name="attributeDisplayLabel">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="attributeName" use="required" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="partDisplayLabel">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="partName" use="required" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="usageNotes" type="xs:string" />
    <xs:element name="readOnly" type="xs:boolean" />
    <xs:element name="repeatable">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:boolean">
                    <xs:attribute name="startingBoxes" use="optional" type="xs:positiveInteger" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="displayedInCatalogingBriefView" type="xs:boolean" />
    <xs:element name="exposedInCatalogingFullView" type="xs:boolean" />
    <xs:element name="displayedInDiscoveryBriefView" type="xs:boolean" />
    <xs:element name="displayedInDiscoveryFullView" type="xs:boolean" />
    <xs:element name="private" type="xs:boolean" />
    
    <xs:element name="defaultValues" type="defaultValuesType" />
    
    <xs:complexType name="defaultValuesType">
        <xs:sequence>
            <xs:element ref="m:field" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== IUBLibTech/photocat2/conf/dummy/repository/collections/demo.xml
<c:configuration xmlns:c="info:photocat/configuration" xmlns:m="info:photocat/metadata"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="info:photocat/configuration http://purl.dlib.indiana.edu/iudl/xml/schema/photocat/field-configuration.xsd">
    <c:collection>
        <c:name>Demonstration collection</c:name>
        <c:id>demo</c:id>
        <c:description>Collection to demonstrate the features of this application.</c:description>
        <c:iconURL>changeme to an image URL</c:iconURL>
        <c:bannerURL></c:bannerURL>
        <c:allowRecordCreation>false</c:allowRecordCreation>
        <c:allowRecordDeletion>false</c:allowRecordDeletion>
    </c:collection>
    <c:item>
        <c:fields definitionId="demo-definitions">
            <c:field type="TITLE">
                <c:displayLabel>Title</c:displayLabel>
                <c:usageNotes> Brief text describing what's featured in the photograph and pointing out other interesting features.</c:usageNotes>
            </c:field>
            <c:field type="ABSTRACT">
                <c:displayLabel>Description</c:displayLabel>
                <c:usageNotes>A description of the photograph's contents for public consumption that
                    is longer and more detailed than the photograph title. Use complete sentences.
                    Information may be speculative if it is reasonable or provides needed discovery
                    for the image. Be declarative in style rather than asking questions. This field
                    is optional. It is not necessary to repeat information from other fields here if
                    no additional information is available. </c:usageNotes>
            </c:field>
            <c:field type="INTERNAL_NOTES">
                <c:usageNotes>Information about the photograph that is for internal use only and
                    should not be shared with the public. Will be searchable in the photo cataloging
                    tool but not by end users.</c:usageNotes>
                <c:displayedInDiscoveryBriefView>false</c:displayedInDiscoveryBriefView>
                <c:displayedInDiscoveryFullView>false</c:displayedInDiscoveryFullView>
            </c:field>
            <c:field type="DATE_TAKEN">
                <c:displayLabel>Date taken (normalized):</c:displayLabel>
                <c:usageNotes>Date the photograph was taken, in the form YYYY-MM-DD. Supply estimated date if no firm date is known. Can provide year, year/month, or year/month/day. If specific year or decade is unknown, can use the form YYY or YY.</c:usageNotes>
            </c:field>
            <c:field type="COPYRIGHT_OWNER">
                <c:displayLabel>Copyright Owner</c:displayLabel>
                <c:usageNotes>When known, enter the individual or organization that owns the copyright on this image. If unknown, leave this field blank.</c:usageNotes>
            </c:field>
            <c:field type="USE_RESTRICTIONS">
                <c:displayLabel>Use Restrictions</c:displayLabel>
                <c:usageNotes>Select from a set of predefined statements that describe any restrictions on use that apply to the materials. Leave blank if there are no restrictions placed on use of the image.</c:usageNotes>
            </c:field>
            <c:field type="PERSON_PICTURED">
                <c:displayLabel>Personal Name</c:displayLabel>
                <c:usageNotes>Full name of a person pictured. List the name in inverted form: Familyname, Givenname.   For the "location of individuals in pictures", enter a description of individuals depicted with information about their location.  Use the form "Row 1â€¦Left to Right, 1st, 2nd, ...".  Click on the little blue arrow to copy (and normalize) names already entered in the list.</c:usageNotes>
                <c:repeatable startingBoxes="5">true</c:repeatable>
                <c:disable type="part" name="affiliation" />
                <c:vocabularySource type="LOCAL" id="archives-person-pictured">
                    <c:valueBinding>entered name</c:valueBinding>
                    <c:sourceConfig>
                        <c:property name="displayName">People</c:property>
                    </c:sourceConfig>
                </c:vocabularySource>
            </c:field>
            <c:field type="EVENT">
                <c:displayLabel>Event Name</c:displayLabel>
                <c:usageNotes>Event depicted in the image. Repeat this field as necessary.</c:usageNotes>
                <c:vocabularySource type="LOCAL" id="local-archivesevent">
                    <c:valueBinding>event name</c:valueBinding>
                    <c:sourceConfig>
                        <c:property name="displayName">Events</c:property>
                    </c:sourceConfig>
                </c:vocabularySource>
            </c:field>
            <c:field type="CITY">
                <c:usageNotes>City represented in the image, if known.</c:usageNotes>
                <c:disable type="part" name="authority"/>
            </c:field>
            <c:field type="US_STATE">
                <c:usageNotes>State represented in this image, if known.</c:usageNotes>
                <c:disable type="part" name="authority"/>
            </c:field>
            <c:field type="MODIFYING_USER" />
            
            <c:defaultValues>
                <m:field fieldType="US_STATE">
                    <m:values>
                        <m:value>
                            <m:part property="state name">Texas</m:part>
                        </m:value>
                    </m:values>
                </m:field>
            </c:defaultValues>
        </c:fields>
    </c:item>
</c:configuration>
